[package]
name = "ekiden-db-trusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sgx_trts = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sgx_tseal = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sgx_tse = { git = "https://github.com/ekiden/rust-sgx-sdk" }
bsdiff = "0.1.3"
bzip2 = "0.3.2"
ekiden-common = { path = "../../common" }
key-manager-client = { path = "../../contracts/key-manager/client" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
protobuf = "1.4.3"
sodalite = "0.3.0"

[build-dependencies]
ekiden-tools = { path = "../../tools" }
protoc-rust = "1.4"

