[workspace]
members = [
  "abci",
  "compute",
  "compute-client",
  "consensus",

  # Key manager is special and must be built before libcontract-trusted in
  # order for libcontract-trusted to include its MRENCLAVE.
  "contracts/key-manager",
  "libcontract/trusted",

  "contracts/token",

  "libcontract/common",
  "libcontract/untrusted",

  "tools",
]
