[workspace]
members = [
  "abci",
  "compute",
  "compute-client",
  "contracts/dummy",
  "contracts/token",
  "contracts/learner",
  "libcontract/common",
  "libcontract/trusted",
  "libcontract/untrusted",
  "libcontract/utils",
  "clients/token",
  "storage",
]
exclude = ["third_party"]
