[workspace]
members = [
  "abci",
  "compute",
  "compute-client",
  "consensus",

  # Key manager is special and must be built before libcontract-trusted in
  # order for libcontract-trusted to include its MRENCLAVE.
  "contracts/key-manager",
  "libcontract/trusted",

  "contracts/dummy",
  "contracts/ethtoken",
  "contracts/token",
  "contracts/dp_credit_scoring",
  "contracts/learner",
  "contracts/iot_learner",

  "libcontract/common",
  "libcontract/untrusted",
  "libcontract/utils",

  "clients/benchmark-token-failover",
  "clients/benchmark-token-transfer",
  "clients/benchmark-token-get-balance",
  "clients/benchmark-dp-credit-scoring-train",
  "clients/benchmark-dp-credit-scoring-infer",
  # "clients/benchmark-iot-learner-train",
  "clients/benchmark-iot-learner-infer",
  "clients/token",
  "clients/dp_credit_scoring",
  "clients/ethtoken",
  "clients/iot_learner",
]
exclude = ["third_party"]
