[workspace]
members = [
  "abci",
  "compute",
  "contracts/token",
  "libcontract",
  "storage",
  "client",
  "libenclave/utils",
  "libenclave/untrusted",
  "libenclave/trusted",
  "enclaves/dummy",
  "examples/enclave_test",
]
