[env]
INTEL_SGX_SDK = "/opt/sgxsdk"
RUST_SGX_SDK = "/sgx"
SGX_MODE = "SIM"
SGX_ARCH = "x64"

[tasks.build]
args = ["build"]

[tasks.build-flow]
dependencies = [
    "pre-build",
    "build",
    "post-build",
]

[tasks.test-flow]
alias = "empty"
