[env]
INTEL_SGX_SDK = "/opt/sgxsdk"
RUST_SGX_SDK = "/sgx"
SGX_ARCH = "x64"

[tasks.default]
alias = "build-flow"

[tasks.env-debug]
env = { "BUILD_MODE" = "debug" }

[tasks.env-release]
env = { "BUILD_MODE" = "release" }

[tasks.env-sgx-xargo]
env = { "RUSTFLAGS" = "-Z force-unstable-if-unmarked", "RUST_TARGET_PATH" = "/code" }

[tasks.build-flow]
dependencies = [
    "env-debug",
    "pre-build",
    "build",
    "post-build",
]

[tasks.build-release-flow]
dependencies = [
    "env-release",
    "pre-build",
    "build-release",
    "post-build",
]

[tasks.build]
dependencies = [
    "build-no-sgx",
    "build-sgx",
]

[tasks.build-release]
dependencies = [
    "build-no-sgx-release",
    "build-sgx-release",
]

[tasks.build-no-sgx]
command = "cargo"
args = ["build"]

[tasks.build-sgx]
dependencies = [ "env-sgx-xargo" ]
command = "xargo"
args = ["build", "--target", "x86_64-unknown-linux-sgx.json"]

[tasks.build-no-sgx-release]
args = ["build", "--release"]

[tasks.build-sgx-release]
dependencies = [ "env-sgx-xargo" ]
command = "xargo"
args = ["build", "--target", "x86_64-unknown-linux-sgx.json", "--release"]

[tasks.test-flow]
alias = "empty"

[tasks.checkstyle]
condition = { channels = [ "nightly" ] }
install_crate = "rustfmt-nightly"
command = "cargo"
args = ["fmt", "--", "--write-mode=diff"]
