[env]
INTEL_SGX_SDK = "/opt/sgxsdk"
RUST_SGX_SDK = "/sgx"
SGX_MODE = "SIM"
SGX_ARCH = "x64"

[tasks.default]
alias = "build-flow"

[tasks.build]
args = ["build"]

[tasks.build-release]
args = ["build", "--release"]

[tasks.env-debug]
env = { "BUILD_MODE" = "debug" }

[tasks.env-release]
env = { "BUILD_MODE" = "release" }

[tasks.build-flow]
dependencies = [
    "env-debug",
    "pre-build",
    "build",
    "post-build",
]

[tasks.build-release-flow]
dependencies = [
    "env-release",
    "pre-build",
    "build-release",
    "post-build",
]


[tasks.test-flow]
alias = "empty"

[tasks.checkstyle]
condition = { channels = [ "nightly" ] }
install_crate = "rustfmt-nightly"
command = "cargo"
args = ["fmt", "--", "--write-mode=diff"]
