[package]
name = "ekiden-core"
version = "0.1.0-alpha.1"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden common functionality (available to both trusted and untrusted parts)"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.1" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.1.0-alpha.1" }
ekiden-rpc-common = { path = "../../rpc/common", version = "0.1.0-alpha.1" }
