[package]
name = "ekiden-core"
version = "0.1.0"
authors = [
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
ekiden-common = { path = "../../common" }
ekiden-enclave-common = { path = "../../enclave/common" }
ekiden-rpc-common = { path = "../../rpc/common" }
