[package]
name = "dp-credit-scoring-client"
version = "0.1.0"
authors = ["Nick Hynes <nhynes@berkeley.edu>"]

[dependencies]
clap = "2.29.1"
client-utils = { path = "../utils" }
compute-client = { path = "../../compute-client" }
dp-credit-scoring-api = { path = "../../contracts/dp_credit_scoring/api", default-features = false, features = ["no-sgx"] }
libcontract-common = { path = "../../libcontract/common" }
protobuf = "1.4.2"
serde-pickle = "0.4.0"
futures = "0.1"
tokio-core = "0.1"
