[package]
name = "libenclave-trusted"
version = "0.1.0"
authors = ["Jernej Kos <jernej@kos.mx>"]
build = "build.rs"

[dependencies]
sgx_types = { path = "/sgx/sgx_types" }
sgx_tstd = { path = "/sgx/sgx_tstd" }
protobuf = { path = "../../third_party/protobuf" }

[build-dependencies]
protoc-rust = "1.4"
