[package]
name = "ekiden-rpc-common"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]
build = "build.rs"

[dependencies]
ekiden-common = { path = "../../common" }
protobuf = "1.4.3"
sodalite = "0.3.0"
byteorder = "1.2.1"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"

[build-dependencies]
ekiden-tools = { path = "../../tools" }
protoc-rust = "1.4"
