[package]
name = "ekiden-enclave-common"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
base64 = "0.9.0"
byteorder = "1.2.1"
ekiden-common = { path = "../../common" }
rand = "0.4"
serde_json = "1.0.9"
