[package]
name = "ekiden-enclave-common"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
base64 = "0.9.0"
byteorder = "1.2.1"
ekiden-common = { path = "../../common" }
serde_json = { git = "https://github.com/ekiden/json", branch = "xargo" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"
