[package]
name = "ekiden-enclave-common"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
default = ["no-sgx"]
no-sgx = ["rand", "byteorder", "serde_json", "base64", "ekiden-common/no-sgx"]
sgx = ["byteorder-sgx", "serde_json-sgx", "base64-sgx", "sgx_types", "sgx_tstd", "sgx_trts", "ekiden-common/sgx"]

[dependencies]
ekiden-common = { path = "../../common", default-features = false }
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", optional = true }
sgx_tstd = { git = "https://github.com/ekiden/rust-sgx-sdk", optional = true }
sgx_trts = { git = "https://github.com/ekiden/rust-sgx-sdk", optional = true }
rand = { version = "0.4", optional = true }
byteorder = { version = "1.2.1", optional = true }
byteorder-sgx = { git = "https://github.com/ekiden/byteorder", optional = true }
serde_json = { version = "1.0.9", optional = true }
serde_json-sgx = { git = "https://github.com/ekiden/json", optional = true }
base64 = { version = "0.9.0", optional = true }
base64-sgx = { git = "https://github.com/ekiden/rust-base64", optional = true }
