version: 2
jobs:
  build:
    docker:
      - image: ekiden/rust-sgx-sdk:latest
    steps:
      - run: git clone --depth=1 https://github.com/baidu/rust-sgx-sdk.git /sgx
      - checkout
      - run: $HOME/.cargo/bin/cargo make build-flow
      - run: $HOME/.cargo/bin/cargo make format
workflows:
  version: 2
  build:
    jobs:
      - build
experimental:
  notify:
    only:
      - master
