version: 2
jobs:
  build:
    docker:
      - image: ekiden/testing
    steps:
      # Set up
      - run: echo 'PS1='"'"'\$ '"'"'; . /root/.bashrc' >> $BASH_ENV
      - checkout
      - run: git clone --branch v0.9.1 https://github.com/baidu/rust-sgx-sdk.git /sgx
      - restore_cache:
          keys:
            - v1-omni-{{ .Branch }}-{{ .Revision }}
            - v1-omni-{{ .Branch }}-
            - v1-omni-master-

      # Build
      - run: cargo make build-flow

      # Rustfmt
      - run: cargo make checkstyle

      # Cargo tests
      #- run: cargo test -p consensus 

      # Test: end-to-end token contract
      - run:
          command: ./target/debug/consensus
          background: true
      - run: tendermint init
      - run:
          command: tendermint node --consensus.create_empty_blocks=false --rpc.laddr tcp://0.0.0.0:46666 --rpc.grpc_laddr tcp://0.0.0.0:46657
          background: true
      - run: echo "$IAS_PKCS12" | base64 --decode --ignore-garbage > client.pfx
      - run:
          command: ./target/debug/compute target/enclave/token.signed.so
          background: true
      - run:
          command: ./target/debug/compute target/enclave/key-manager.signed.so -p 9003 --disable-key-manager
          background: true
      - run: ./target/debug/token-client --mr-enclave $(python scripts/parse_enclave.py target/enclave/token.signed.so 2>/dev/null | grep ENCLAVEHASH | cut -f2)

      # Save cache
      - save_cache:
          key: v1-omni-{{ .Branch }}-{{ .Revision }}
          paths:
            - /root/.cargo
            - target
workflows:
  version: 2
  build:
    jobs:
      - build
experimental:
  notify:
    branches:
      only:
        - master
