[package]
name = "ekiden-rpc-trusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sgx_trts = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sgx_tseal = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sgx_tse = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sodalite = "0.3.0"
protobuf = "1.4.3"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
ekiden-common = { path = "../../common" }
ekiden-enclave-common = { path = "../../enclave/common" }
ekiden-rpc-common = { path = "../common" }
ekiden-rpc-client = { path = "../client" }
futures = "0.1.18"

[build-dependencies]
ekiden-tools = { path = "../../tools" }
