[package]
name = "rpc_untrusted"
version = "0.1.0"
authors = ["Jernej Kos <jernej@kos.mx>"]
build = "build.rs"

[dependencies]
sgx_types = { path = "/sgx/sgx_types" }
sgx_urts = { path = "/sgx/sgx_urts" }
protobuf = "1.4.2"

[build-dependencies]
protoc-rust = "1.4"
