[package]
name = "benchmark-iot-learner-train"
version = "0.1.0"
authors = ["Nick", "Warren"]

[dependencies]
clap = "2.29.1"
client-utils = { path = "../utils", features = ["benchmark"] }
compute-client = { path = "../../compute-client" }
learner-api = { path = "../../contracts/learner/api", default-features = false, features = ["no-sgx"] }
learner = { path = "../../contracts/learner", default-features = false, features = ["no-sgx"] }
libcontract-common = { path = "../../libcontract/common" }
protobuf = "1.4.2"
lazy_static = "1.0"
futures = "0.1"
tokio-core = "0.1"
