[package]
name = "ekiden-rpc-client"
version = "0.1.0-alpha.0"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden RPC client"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.0" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.1.0-alpha.0" }
ekiden-rpc-common = { path = "../common", version = "0.1.0-alpha.0" }
protobuf = "1.4.3"
sodalite = "0.3.0"

[target.'cfg(target_env = "sgx")'.dependencies]
futures-sgx = { git = "https://github.com/ekiden/futures-rs" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-compute-api = { path = "../../compute/api", version = "0.1.0-alpha.0" }
byteorder = "1.2.1"
futures = "0.1"
grpc = "0.2.1"
httpbis  = "0.4.1"
rand = "0.4"
tls-api  = "0.1.12"
tokio-core = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.0" }
protoc-rust-grpc = "0.2.1"
