[package]
name = "ekiden-rpc-client"
version = "0.1.0"
authors = ["Jernej Kos <jernej@kos.mx>"]

[dependencies]
byteorder = "1.2.1"
compute-api = { path = "../../compute/api" }
ekiden-common = { path = "../../common" }
ekiden-enclave-common = { path = "../../enclave/common" }
ekiden-rpc-common = { path = "../common" }
futures = "0.1"
grpc = "0.2.1"
httpbis  = "0.4.1"
protobuf = "1.4.3"
rand = "0.4"
sodalite = "0.3.0"
tls-api  = "0.1.12"
tokio-core = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools" }
protoc-rust-grpc = "0.2.1"
