[package]
name = "benchmark-token-failover"
version = "0.1.0"
authors = [
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
client-utils = { path = "../utils" }
libcontract-common = { path = "../../libcontract/common" }
compute-client = { path = "../../compute-client" }
token-api = { path = "../../contracts/token/api" }
clap = "2.29.1"
rand = "0.4"
time = "0.1"
futures = "0.1"
tokio-core = "0.1"
