---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: ethermint
  labels:
    app: ethermint
spec:
  ports:
    - port: 46656
      name: tendermint-p2p
  clusterIP: None
  selector:
    app: ethermint
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tendermint-config
data:
  seeds: "ethermint-0,ethermint-1,ethermint-2,ethermint-3"
  validators: "ethermint-0,ethermint-1,ethermint-2,ethermint-3"
  validator.power: "10"
  genesis.json: |-
    {
      "genesis_time": "2018-01-25T00:00:00.000Z",
      "chain_id": "ethermint-test-net",
      "validators": [],
      "app_hash": ""
    }
  pub_key_nginx.conf: |-
    server {
      listen 80 default_server;
      listen [::]:80 default_server ipv6only=on;
      location /pub_key.json { root /usr/share/nginx/; }
    }
  ethermint-keystore.json: |-
    {
      "address":"7eff122b94897ea5b0e2a9abf47b86337fafebdc",
      "crypto":{
        "cipher":"aes-128-ctr",
        "ciphertext":"19de8a919e2f4cbdde2b7352ebd0be8ead2c87db35fc8e4c9acaf74aaaa57dad",
        "cipherparams":{"iv":"ba2bd370d6c9d5845e92fbc6f951c792"},
        "kdf":"scrypt",
        "kdfparams":{
          "dklen":32,
          "n":262144,
          "p":1,
          "r":8,
          "salt":"c7cc2380a96adc9eb31d20bd8d8a7827199e8b16889582c0b9089da6a9f58e84"
        },
        "mac":"ff2c0caf051ca15d8c43b6f321ec10bd99bd654ddcf12dd1a28f730cc3c13730"
      },
      "id":"f86a62b4-0621-4616-99af-c4b7f38fcc48",
      "version":3
    }
  ethermint-genesis.json: |-
    {
        "config": {
            "chainId": 15,
            "homesteadBlock": 0,
            "eip155Block": 0,
            "eip158Block": 0
        },
        "nonce": "0xdeadbeefdeadbeef",
        "timestamp": "0x00",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "difficulty": "0x40",
        "gasLimit": "0x8000000",
        "alloc": {
            "0x7eff122b94897ea5b0e2a9abf47b86337fafebdc": { "balance": "100000000000000" },
            "0xc6713982649D9284ff56c32655a9ECcCDA78422A": { "balance": "10000000000000000000000000000000000" }
        }
    }
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ethermint-budget
spec:
  selector:
    matchLabels:
      app: ethermint
  minAvailable: 2
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: ethermint
spec:
  selector:
    matchLabels:
      app: ethermint
  serviceName: ethermint
  replicas: 4
  template:
    metadata:
      labels:
        app: ethermint
    spec:
      initContainers:
        # An initialization container, which generates the validator key pair if it doesn't yet
        # exist. The public part is extracted and copied to /tendermint/pub_key.json, so it can
        # be served by the public-key container. This allows nodes to discover public keys of
        # each other.
        - name: generate-validator
          image: tendermint/tendermint:0.13.0
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - "-c"
            - |
              set -ex
              if [ ! -f /tendermint/priv_validator.json ]; then
                tendermint gen_validator > /tendermint/priv_validator.json
                # pub_key.json will be served by public-key container
                cat /tendermint/priv_validator.json | jq ".pub_key" > /tendermint/pub_key.json
              fi
          volumeMounts:
            - name: tmdir
              mountPath: /tendermint

      containers:
        # Container serving the Tendermint node's public key.
        - name: public-key
          imagePullPolicy: IfNotPresent
          image: nginx:latest
          ports:
            - containerPort: 80
              name: public-key
          command:
            - bash
            - "-c"
            - |
              set -ex
              # fixes 403 Permission Denied (open() "/tendermint/pub_key.json" failed (13: Permission denied))
              # => we cannot serve from /tendermint, so we copy the file
              mkdir -p /usr/share/nginx
              cp /tendermint/pub_key.json /usr/share/nginx/pub_key.json
              nginx -g "daemon off;"
          volumeMounts:
            - name: tmdir
              mountPath: /tendermint
            - mountPath: /etc/nginx/conf.d/pub_key.conf
              name: tmconfigdir
              subPath: pub_key_nginx.conf

        # Container running a Tendermint node.
        - name: tendermint
          imagePullPolicy: IfNotPresent
          image: tendermint/tendermint:0.13.0
          ports:
            - containerPort: 46656
              name: tendermint-p2p
          env:
            - name: SEEDS
              valueFrom:
                configMapKeyRef:
                  name: tendermint-config
                  key: seeds
            - name: VALIDATOR_POWER
              valueFrom:
                configMapKeyRef:
                  name: tendermint-config
                  key: validator.power
            - name: VALIDATORS
              valueFrom:
                configMapKeyRef:
                  name: tendermint-config
                  key: validators
            - name: TMHOME
              value: /tendermint
          command:
            - bash
            - "-c"
            - |
              set -ex

              # Copy genesis file template.
              cp /etc/tendermint/genesis.json /tendermint/genesis.json

              # Fill genesis file with validators.
              IFS=',' read -ra VALS_ARR <<< "$VALIDATORS"
              fqdn_suffix=$(hostname -f | sed 's#[^.]*\.\(\)#\1#')
              for v in "${VALS_ARR[@]}"; do
                # Wait until validator generates priv/pub key pair.
                set +e

                curl -s --fail "http://$v.$fqdn_suffix/pub_key.json" > /dev/null
                ERR=$?
                while [ "$ERR" != 0 ]; do
                  sleep 5
                  curl -s --fail "http://$v.$fqdn_suffix/pub_key.json" > /dev/null
                  ERR=$?
                done
                set -e

                # Add validator to genesis file along with its pub_key.
                curl -s "http://$v.$fqdn_suffix/pub_key.json" | jq ". as \$k | {pub_key: \$k, power: $VALIDATOR_POWER, name: \"$v\"}" > pub_validator.json
                cat /tendermint/genesis.json | jq ".validators |= .+ [$(cat pub_validator.json)]" > tmpgenesis && mv tmpgenesis /tendermint/genesis.json
                rm pub_validator.json
              done

              # Construct seeds.
              IFS=',' read -ra SEEDS_ARR <<< "$SEEDS"
              seeds=()
              for s in "${SEEDS_ARR[@]}"; do
                seeds+=("$s.$fqdn_suffix:46656")
              done
              seeds=$(IFS=','; echo "${seeds[*]}")

              tendermint node \
                --p2p.seeds="$seeds" \
                --moniker="`hostname`" \
                --consensus.create_empty_blocks=false

          volumeMounts:
            - name: tmdir
              mountPath: /tendermint
            - name: tmconfigdir
              mountPath: /etc/tendermint/genesis.json
              subPath: genesis.json

        # Container running an Ethermint node.
        - name: ethermint
          imagePullPolicy: IfNotPresent
          image: tendermint/ethermint:develop
          command:
            - bash
            - "-c"
            - |
              cd /ethermint-init
              ethermint --datadir /ethermint init

              ethermint \
                --datadir /ethermint \
                --rpc \
                --rpcaddr=0.0.0.0 \
                --ws \
                --wsaddr=0.0.0.0 \
                --rpcapi eth,net,web3,personal,admin

          volumeMounts:
            - name: emdir
              mountPath: /ethermint
            - mountPath: /ethermint-init/genesis.json
              name: tmconfigdir
              subPath: ethermint-genesis.json
            - mountPath: /ethermint-init/keystore/UTC--2016-10-21T22-30-03.071787745Z--7eff122b94897ea5b0e2a9abf47b86337fafebdc
              name: tmconfigdir
              subPath: ethermint-keystore.json

      volumes:
        - name: tmconfigdir
          configMap:
            name: tendermint-config


  volumeClaimTemplates:
    - metadata:
        name: tmdir
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: emdir
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
