[package]
name = "ekiden-db-untrusted"
version = "0.1.0-alpha.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
sgx-simulation = []

[dependencies]
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.7-ekiden1" }
ekiden-common = { path = "../../common", version = "0.1.0-alpha.0" }
ekiden-enclave-untrusted = { path = "../../enclave/untrusted", version = "0.1.0-alpha.0" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.0" }
