[package]
name = "enclave_dummy"
version = "0.1.0"
authors = ["Jernej Kos <jernej@kos.mx>"]
build = "build.rs"

[lib]
name = "enclave_dummy"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
sgx_types = { path = "/sgx/sgx_types" }
sgx_tstd = { path = "/sgx/sgx_tstd" }
sgx_rand = { path = "/sgx/sgx_rand" }
libenclave-trusted = { path = "../../libenclave/trusted" }

[build-dependencies]
protoc-rust = "1.4"
libenclave-utils = { path = "../../libenclave/utils" }
