[package]
name = "contracts"
version = "0.1.0"
authors = ["Raymond Cheng <me@raymondcheng.net>"]

[dependencies]
libcontract = { path = "../libcontract" }

[[bin]]
name = "token"
path = "src/token/main.rs"
