[package]
name = "compute"
version = "0.1.0"
authors = ["Raymond Cheng <me@raymondcheng.net>"]
build = "build.rs"

[dependencies]
libcontract_untrusted = { path = "../libcontract/untrusted" }

[build-dependencies]
libcontract_utils = { path = "../libcontract/utils" }
