[package]
name = "compute"
version = "0.1.0"
authors = ["Raymond Cheng <me@raymondcheng.net>"]
build = "build.rs"

[dependencies]
libcontract-untrusted = { path = "../libcontract/untrusted" }
protobuf = "1.4.2"

[build-dependencies]
libcontract-utils = { path = "../libcontract/utils" }
protoc-rust = "1.4"
