[package]
name = "ekiden-trusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
ekiden-rpc-trusted = { path = "../../rpc/trusted" }
ekiden-db-trusted = { path = "../../db/trusted" }
