[package]
name = "libcontract_app"
version = "0.1.0"
authors = ["Raymond Cheng <me@raymondcheng.net>"]
build = "build.rs"

[lib]
path = "src/lib_app.rs"

[dependencies]
protobuf = "1.4.2"

[build-dependencies]
protoc-rust = "1.4"
