[package]
name = "ekiden-enclave-untrusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
sgx-simulation = []

[dependencies]
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", branch = "xargo" }
sgx_urts = { git = "https://github.com/ekiden/rust-sgx-sdk", branch = "xargo" }
ekiden-common = { path = "../../common" }

[build-dependencies]
ekiden-tools = { path = "../../tools" }
