[package]
name = "ekiden-enclave-untrusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
sgx-simulation = []

[dependencies]
sgx_types = { path = "../../third_party/rust-sgx-sdk/sgx_types" }
sgx_urts = { path = "../../third_party/rust-sgx-sdk/sgx_urts" }
ekiden-common = { path = "../../common" }

[build-dependencies]
ekiden-tools = { path = "../../tools" }
