[package]
name = "libcontract-untrusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
sgx-simulation = []

[dependencies]
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk" }
sgx_urts = { git = "https://github.com/ekiden/rust-sgx-sdk" }
protobuf = "1.4.2"
libcontract-common = { path = "../common", features = ["no-sgx"], default-features = false }

[build-dependencies]
libcontract-utils = { path = "../utils" }
