[package]
name = "ekiden-rpc-untrusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
sgx-simulation = []

[dependencies]
sgx_types = { path = "../../third_party/rust-sgx-sdk/sgx_types" }
sgx_urts = { path = "../../third_party/rust-sgx-sdk/sgx_urts" }
protobuf = "1.4.2"
lazy_static = "1.0"
ekiden-common = { path = "../../common" }
ekiden-enclave-untrusted = { path = "../../enclave/untrusted" }
ekiden-rpc-common = { path = "../common" }

[build-dependencies]
ekiden-tools = { path = "../../tools" }
