[package]
name = "learner"
version = "0.1.0"
authors = ["Nick Hynes <nhynes@berkeley.edu>"]
build = "build.rs"

[lib]
name = "learner"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
learner-api = { path = "./api", features = ["sgx"], default-features = false }
libcontract-common = { path = "../../libcontract/common", features = ["sgx"], default-features = false }
libcontract-trusted = { path = "../../libcontract/trusted" }
protobuf-sgx = { git = "https://github.com/ekiden/rust-protobuf" }
rusty-machine = { git = "https://github.com/ekiden/rust-sgx-sdk" }
serde_cbor = { git = "https://github.com/ekiden/cbor" }
sgx_tstd = { git = "https://github.com/ekiden/rust-sgx-sdk" }

[build-dependencies]
libcontract-utils = { path = "../../libcontract/utils" }
