[package]
name = "enclave_test"
version = "0.1.0"
authors = ["Jernej Kos <jernej@kos.mx>"]
build = "build.rs"

[dependencies]
libenclave-untrusted = { path = "../../libenclave/untrusted" }
protobuf = "1.4.2"

[build-dependencies]
libenclave-utils = { path = "../../libenclave/utils" }
protoc-rust = "1.4"
