[package]
name = "ekiden-tools"
version = "0.1.0-alpha.1"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden build tools"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
mktemp = "0.3.1"
cc = "1.0"
protoc = "1.4"
protoc-rust = "1.4"
protobuf = "1.4"
sgx_edl = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.7-ekiden1" }
clap = "2.29.1"
ansi_term = "0.11"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
ekiden-common = { path = "../common", version = "0.1.0-alpha.1" }

[[bin]]
name = "cargo-ekiden"
path ="bin/main.rs"
