[package]
name = "key-manager-client"
version = "0.1.0"
authors = ["Jernej Kos <jernej@kos.mx>"]

[dependencies]
ekiden-common = { path = "../../../common" }
ekiden-enclave-common = { path = "../../../enclave/common" }
ekiden-rpc-client = { path = "../../../rpc/client" }
ekiden-rpc-common = { path = "../../../rpc/common" }
ekiden-rpc-trusted = { path = "../../../rpc/trusted" }
key-manager-api = { path = "../api" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }

[build-dependencies]
ekiden-tools = { path = "../../../tools" }
