[package]
name = "ekiden-key-manager-client"
version = "0.1.0-alpha.0"
authors = ["Jernej Kos <jernej@kos.mx>"]

[dependencies]
ekiden-common = { path = "../../../common", version = "0.1.0-alpha.0" }
ekiden-enclave-common = { path = "../../../enclave/common", version = "0.1.0-alpha.0" }
ekiden-rpc-client = { path = "../../../rpc/client", version = "0.1.0-alpha.0" }
ekiden-rpc-common = { path = "../../../rpc/common", version = "0.1.0-alpha.0" }
ekiden-rpc-trusted = { path = "../../../rpc/trusted", version = "0.1.0-alpha.0" }
ekiden-key-manager-api = { path = "../api", version = "0.1.0-alpha.0" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
