[package]
name = "libcontract-trusted"
version = "0.1.0"
authors = ["Raymond Cheng <me@raymondcheng.net>"]
build = "build.rs"

[features]
stats = []
datasets = []

[dependencies]
sgx_types = { path = "/sgx/sgx_types" }
sgx_tstd = { path = "/sgx/sgx_tstd" }
protobuf = { path = "../../third_party/protobuf" }

[build-dependencies]
protoc-rust = "1.4"
