[package]
name = "libcontract-trusted"
version = "0.1.0"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
sgx_types = { path = "/sgx/sgx_types" }
sgx_tstd = { path = "/sgx/sgx_tstd" }
sgx_trts = { path = "/sgx/sgx_trts" }
protobuf-sgx = { path = "../../third_party/protobuf" }
libcontract-common = { path = "../common", features = ["sgx"], default-features = false }
sodalite = "0.3.0"
